swagger: '2.0'
info:
  description: A Simple database browser API
  title: Talend API
  version: v1
host: localhost:8088
schemes:
  - http
paths:
  /service_details:
    get:
      summary: Get service details.
      operationId: "serviceDetails"
      consumes:
        - application/json
      parameters:
        - in: query
          name: service_code
          type: string
          description: 'The service code to be lookedup.'
          default: 'wn106'
      responses:
        200:
          description: Success response
          schema:
            type: object
            properties:
              services:
                type: object
                properties:
                  service_details:
                    type: object
                    properties:
                      id: 
                        type: integer
                        example: 1
                      service_code:
                        type: string
                        example: 'wn106'
                      partner_id:
                        type: integer
                        example: 10
                      name:
                        type: string
                        example: 'service106'
                      managed:
                        type: boolean
                        example: false
                      global_service_whitelist:
                        type: boolean
                        example: false
                      enable_service_whitelist:
                        type: boolean
                        example: false
                      global_service_blacklist:
                        type: boolean
                        example: false
                      enable_service_blacklist:
                        type: boolean
                        example: false
                      enable_global_subscription_blacklist:
                        type: boolean
                        example: false
                      enable_global_charging_blacklist:
                        type: boolean
                        example: false
                      service_type:
                        type: string
                        enum: 
                          - 'on-demand'
                          - 'subscription'
                        example: 'on-demand'
        404:
          description: Service Code not found                      
  /partner_dnd:
    get:
      summary: Lookup partner dnd.
      operationId: "partnerDnd"
      consumes:
        - application/json
      parameters:
        - in: query
          name: 'partner_id'
          type: integer
          description: 'The partner id to be lookedup.'
          default: 231
        - in: query
          name: 'msisdn'
          type: string
          description: 'The msisdn to be lookedup.'
          default: '97733554421'
      responses:
        200:
          description: Success response
          schema:
            type: object
            properties:
              partner_dnd:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
        400:
          description: Invalid request                         
  /service_whitelist:
    get:
      summary: Lookup service whitelist.
      operationId: "serviceWhitelist"
      consumes:
        - application/json
      parameters:
        - in: query
          name: service_id
          type: integer
          description: 'The service id to be lookedup.'
          default: 231
        - in: query
          name: msisdn
          type: string
          description: 'The msisdn to be lookedup.'
          default: '97733554421'
      responses:
        200:
          description: Success response
          schema:
            type: object
            properties:
              service_whitelist:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
        400:
          description: Invalid request
  /service_group_whitelist:
    get:
      summary: Lookup service group whitelist.
      operationId: "serviceGroupWhitelist"
      consumes:
        - application/json
      parameters:
        - in: query
          name: service_id
          type: integer
          description: 'The service id to be lookedup.'
          default: 231
        - in: query
          name: msisdn
          type: string
          description: 'The msisdn to be lookedup.'
          default: '97733554421'
      responses:
        200:
          description: Success response
          schema:
            type: object
            properties:
              service_group_whitelist:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
        400:
          description: Invalid request
  /service_blacklist:
    get:
      summary: Lookup service blacklist.
      operationId: "serviceBlacklist"
      consumes:
        - application/json
      parameters:
        - in: query
          name: service_id
          type: integer
          description: 'The service id to be lookedup.'
          default: 231
        - in: query
          name: msisdn
          type: string
          description: 'The msisdn to be lookedup.'
          default: '97733554421'
      responses:
        200:
          description: Success response
          schema:
            type: object
            properties:
              service_blacklist:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
        400:
          description: Invalid request
  /service_group_blacklist:
    get:
      summary: Lookup service group blacklist.
      operationId: "serviceGroupBlacklist"
      consumes:
        - application/json
      parameters:
        - in: query
          name: service_id
          type: integer
          description: 'The service id to be lookedup.'
          default: 231
        - in: query
          name: msisdn
          type: string
          description: 'The msisdn to be lookedup.'
          default: '97733554421'
      responses:
        200:
          description: Success response
          schema:
            type: object
            properties:
              service_group_blacklist:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
        400:
          description: Invalid request 
  /device_blacklist:
    get:
      summary: Lookup device blacklist.
      operationId: "deviceBlacklist"
      consumes:
        - application/json
      parameters:
        - in: query
          name: service_id
          type: integer
          description: 'The service id to be lookedup.'
          default: 231
        - in: query
          name: model_code
          type: string
          description: 'The model code to be lookedup.'
          default: 'nova3i'
      responses:
        200:
          description: Success response
          schema:
            type: object
            properties:
              device_blacklist:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
        400:
          description: Invalid request   
  /global_subscription_blacklist:
    get:
      summary: Lookup global subscription blacklist.
      operationId: "serviceGlobalSubscriptionBlacklist"
      consumes:
        - application/json
      parameters:
        - in: query
          name: msisdn
          type: string
          description: 'The msisdn to be lookedup.'
          default: '97733554421'
      responses:
        200:
          description: Success response
          schema:
            type: object
            properties:
              global_subscription_blacklist:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
        400:
          description: Invalid request 
  /global_charging_blacklist:
    get:
      summary: Lookup global charging blacklist.
      operationId: "serviceGlobalChargingBlacklist"
      consumes:
        - application/json
      parameters:
        - in: query
          name: msisdn
          type: string
          description: 'The msisdn to be lookedup.'
          default: '97733554421'
      responses:
        200:
          description: Success response
          schema:
            type: object
            properties:
              global_charging_blacklist:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
        400:
          description: Invalid request 
